name: flutter_easy
description: A common Flutter package.
version: 3.1.4
homepage: https://github.com/OctMon/flutter_easy

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ===============================================================================
  # Network request result
  # pub: https://pub.dev/packages/session
  # git: https://github.com/OctMon/session
  # ———————————————————————————————————————————————————————————————————————————————
  session: ^1.1.4
  dio: ^5.3.0
  # ===============================================================================

  # ===============================================================================
  # Generate RFC4122(v1,v4,v5) UUIDs
  # pub: https://pub.dev/packages/uuid
  # git: https://github.com/Daegalus/dart-uuid
  # ———————————————————————————————————————————————————————————————————————————————
  uuid: ^3.0.7
  # ===============================================================================

  # ===============================================================================
  # A set of high-level APIs over PointyCastle for two-way cryptography.
  # pub: https://pub.dev/packages/encrypt
  # git: https://github.com/leocavalcante/encrypt
  # AES with PKCS7 padding
  # RSA with PKCS1 and OAEP encoding
  # Salsa20
  # ———————————————————————————————————————————————————————————————————————————————
  encrypt: ^5.0.1
  crypto: ^3.0.3
  convert: ^3.1.1
  # ===============================================================================

  # ===============================================================================
  # Flutter EasyLoading
  # pub：https://pub.dev/packages/flutter_easyloading
  # git：https://github.com/kokohuang/flutter_easyloading
  # desc： ✨A clean and lightweight loading/toast widget for Flutter, easy to use without context, support iOS、Android and Web
  # ===============================================================================
  flutter_easyloading: ^3.0.5

  # ===============================================================================
  # 共享首选项插件
  # pub：https://pub.dev/packages/shared_preferences
  # git：https://github.com/flutter/plugins/tree/master/packages/shared_preferences
  # desc：包装NSUserDefaults（在iOS上）和SharedPreferences（在Android上），为简单数据提供持久存储。
  # 数据异步保存到磁盘。 这两个平台都不能保证在返回后将写操作持久化到磁盘，并且该插件不得用于存储关键数据。
  # ===============================================================================
  shared_preferences: ^2.2.0
  shared_preferences_platform_interface: ^2.3.0
  shared_preferences_web: ^2.2.0

  # ===============================================================================
  # This Flutter plugin provides an API for querying information about an application package.
  # pub: https://pub.dev/packages/package_info_plus
  # git: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/package_info_plus
  # ———————————————————————————————————————————————————————————————————————————————
  package_info_plus: ^4.1.0
  # ===============================================================================

  # ===============================================================================
  # A Flutter plugin for launching a URL in the mobile platform. Supports iOS and Android.
  # pub: https://pub.dev/packages/url_launcher
  # git: https://github.com/flutter/plugins/tree/master/packages/url_launcher
  # ———————————————————————————————————————————————————————————————————————————————
  url_launcher: ^6.1.12
  # ===============================================================================

  # ===============================================================================
  # Download, cache and show images in a flutter app
  # pub: https://pub.dartlang.org/packages/cached_network_image
  # git: https://github.com/renefloor/flutter_cached_network_image
  # ———————————————————————————————————————————————————————————————————————————————
  cached_network_image: ^3.2.3
  cached_network_image_platform_interface: ^2.0.0
  flutter_cache_manager: ^3.3.1
  path_provider: ^2.1.0
  path: ^1.8.2
  # ===============================================================================

  # ===============================================================================
  # a widget provided to the flutter scroll component drop-down refresh and pull up load.
  # pub: https://pub.dev/packages/pull_to_refresh
  # git: https://github.com/peng8350/flutter_pulltorefresh
  # ———————————————————————————————————————————————————————————————————————————————
  pull_to_refresh: ^2.0.0
  # ===============================================================================

  # ===============================================================================
  # 无限轮播
  # pub: https://pub.dev/packages/card_swiper
  # git: https://github.com/TheAnkurPanchani/card_swiper
  # desc：flutter最强大的swiper, 多种布局方式，无限轮播，Android和IOS双端适配.
  # ===============================================================================
  card_swiper: ^3.0.1

  # ===============================================================================
  # 名称： GetX
  # pub：https://pub.dev/packages/get
  # get：https://github.com/jonataslaw/getx
  # desc：Open screens/snackbars/dialogs without context, manage states and inject dependencies easily with GetX
  # ===============================================================================
  get: ^4.6.5

  # ===============================================================================
  # 名称： It can distinguish between cellular vs WiFi connection.
  # pub：https://pub.dev/packages/connectivity_plus
  # get：https://github.com/fluttercommunity/plus_plugins/tree/main/packages/connectivity_plus/connectivity_plus
  # desc：On Android, this does not guarantee connection to Internet.
  # For instance, the app might have wifi access but it might be a VPN or a hotel WiFi > with no access.
  # ===============================================================================
  connectivity_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#  - images/a_dot_burr.jpeg
#  - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
