name: flutter_easy
description: A common Flutter package.
version: 2.0.0
homepage: https://github.com/OctMon/flutter_easy

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ===============================================================================
  # Network request result
  # pub: https://pub.dev/packages/session
  # git: https://github.com/OctMon/session
  # ———————————————————————————————————————————————————————————————————————————————
  session: ^0.5.1
  dio: ^3.0.10
  # ===============================================================================

  # ===============================================================================
  # Small, easy to use and extensible logger which prints beautiful logs.
  # pub: https://pub.dev/packages/logger
  # git: https://github.com/leisim/logger
  # ———————————————————————————————————————————————————————————————————————————————
  logger: ^1.0.0
  # ===============================================================================

  # ===============================================================================
  # Generate RFC4122(v1,v4,v5) UUIDs
  # pub: https://pub.dev/packages/uuid
  # git: https://github.com/Daegalus/dart-uuid
  # ———————————————————————————————————————————————————————————————————————————————
  uuid: ^2.2.2
  # ===============================================================================

  # ===============================================================================
  # A set of high-level APIs over PointyCastle for two-way cryptography.
  # pub: https://pub.dev/packages/encrypt
  # git: https://github.com/leocavalcante/encrypt
  # AES with PKCS7 padding
  # RSA with PKCS1 and OAEP encoding
  # Salsa20
  # ———————————————————————————————————————————————————————————————————————————————
  encrypt: ^4.1.0
  crypto: ^2.1.5
  convert: ^2.1.1
  # ===============================================================================

  # ===============================================================================
  # a pure flutter toast library You can completely customize the style of toast.
  # pub: https://pub.dev/packages/oktoast
  # git: https://github.com/OpenFlutter/flutter_oktoast
  # ———————————————————————————————————————————————————————————————————————————————
  oktoast: ^3.0.0
  # ===============================================================================

  # ===============================================================================
  # 名称：共享首选项插件
  # 来源：https://pub.dev/packages/shared_preferences
  # GitHub：https://github.com/flutter/plugins/tree/master/packages/shared_preferences
  # 说明：包装NSUserDefaults（在iOS上）和SharedPreferences（在Android上），为简单数据提供持久存储。
  # 数据异步保存到磁盘。 这两个平台都不能保证在返回后将写操作持久化到磁盘，并且该插件不得用于存储关键数据。
  # ===============================================================================
  shared_preferences: ^2.0.5
  shared_preferences_windows: ^2.0.0
  shared_preferences_web: ^2.0.0

  # ===============================================================================
  # This Flutter plugin provides an API for querying information about an application package.
  # pub: https://pub.dev/packages/package_info
  # git: https://github.com/flutter/plugins/tree/master/packages/package_info
  # ———————————————————————————————————————————————————————————————————————————————
  package_info: ^2.0.0
  # ===============================================================================

  # ===============================================================================
  # A Flutter plugin for launching a URL in the mobile platform. Supports iOS and Android.
  # pub: https://pub.dev/packages/url_launcher
  # git: https://github.com/flutter/plugins/tree/master/packages/url_launcher
  # ———————————————————————————————————————————————————————————————————————————————
  url_launcher: ^6.0.2
  # ===============================================================================

  # ===============================================================================
  # Download, cache and show images in a flutter app
  # pub: https://pub.dartlang.org/packages/cached_network_image
  # git: https://github.com/renefloor/flutter_cached_network_image
  # ———————————————————————————————————————————————————————————————————————————————
  cached_network_image: ^2.5.1
  flutter_cache_manager: ^2.1.2
  path_provider: ^2.0.1
  path: ^1.8.0
  # ===============================================================================

  # ===============================================================================
  # A widget provided to the flutter scroll component pull-refresh and push-load.
  # pub: https://pub.dev/packages/flutter_easyrefresh
  # git: https://github.com/xuelongqy/flutter_easyrefresh
  # ———————————————————————————————————————————————————————————————————————————————
  flutter_easyrefresh: ^2.1.8
  # ===============================================================================

  # ===============================================================================
  # 名称：无限轮播
  # 来源：https://pub.dev/packages/flutter_swiper
  # GitHub：https://github.com/best-flutter/flutter_swiper
  # 说明：flutter最强大的swiper, 多种布局方式，无限轮播，Android和IOS双端适配.
  # ===============================================================================
  flutter_swiper: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#  - images/a_dot_burr.jpeg
#  - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
